# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/100_data.ipynb.

# %% auto 0
__all__ = ['normalize', 'normalize_all', 'make_train_test']

# %% ../../nbs/100_data.ipynb 3
def normalize(data:dict, measurement:str):
    ansur=pd.read_csv('../data/processed/ANSURIImalefemale.csv')
    avg_m = ansur[measurement].mean()
    std_m = ansur[measurement].std()
    data[measurement] = (data[measurement] - avg_m) / std_m
    return data

# %% ../../nbs/100_data.ipynb 4
def normalize_all(data, measurement:list):
    for m in measurement:
        data = normalize(data, m)
    return data

# %% ../../nbs/100_data.ipynb 7
def make_train_test(data, test_size:float):
    train, test = train_test_split(data, test_size=test_size, shuffle=True, random_state=42)
    return train, test
