# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/anthropmass',
                'doc_host': 'https://sannasann.github.io',
                'git_url': 'https://github.com/sannasann/anthropmass',
                'lib_path': 'anthropmass'},
  'syms': {'anthropmass.core': {'anthropmass.core.foo': ('core.html#foo', 'anthropmass/core.py')}}}
