# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/201_anthropometry.ipynb.

# %% auto 0
__all__ = ['make_pickle']

# %% ../nbs/201_anthropometry.ipynb 2
import pickle

# %% ../nbs/201_anthropometry.ipynb 3
def make_pickle(model, kindofmodel, measurement):
    with open(f'../output/anthro_models/{kindofmodel}/pickle_{measurement}_{kindofmodel}','wb') as file:
        pickle.dump(model,file)
