# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/200_anthropometry.ipynb.

# %% auto 0
__all__ = ['testis', 'test2']

# %% ../nbs/200_anthropometry.ipynb 2
def testis():
    return 2+2

# %% ../nbs/200_anthropometry.ipynb 3
def test2():
    return 2
